### ISSUE TITLE
[Feature Request] Add support for scss linting rules

### ISSUE THREAD

**Issue by Celtech** [zhilidali/stylelint-config-tailwindcss#2]
# Overview

This package is awesome, but when you have certain SCSS packages added, tailwind rules will fail.

## Story 

When using the package `stylelint-config-sass-guidelines`, we enable scss specific rules that tailwind rules fail on.

```
packages/app/src/assets/css/index.css
 1:1  ✖  Unexpected unknown at-rule "@tailwind"  scss/at-rule-no-unknown
 2:1  ✖  Unexpected unknown at-rule "@tailwind"  scss/at-rule-no-unknown
 3:1  ✖  Unexpected unknown at-rule "@tailwind"  scss/at-rule-no-unknown
```

## Acceptance Criteria

Support the `scss/at-rule-no-unknown` rules for tailwind

## Possible implementation

```diff
// index.js
module.exports = {
  rules: {
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'tailwind',
          'apply',
          'layer',
          /** tailwindcss v1, v2 */
          'variants',
          'responsive',
          'screen',
        ],
      },
    ],
+   'scss/at-rule-no-unknown': [
+     true,
+     {
+       ignoreAtRules: [
+         'tailwind',
+         'apply',
+         'layer',
+         'variants',
+         'responsive',
+         'screen'
+       ]
+     }
+   ],
    'function-no-unknown': [
      true,
      {
        ignoreFunctions: ['theme'],
      },
    ],
  },
};
```

**Comment by zhilidali** [comment]
Thank you for your Feature Request, please update the latest version and try using `stylelint-config-tailwindcss/scss` instead of `stylelint-config-tailwindcss`，For details, see [commit](https://github.com/zhilidali/stylelint-config-tailwindcss/commit/62252359256671cca2179a2db12e28bbcab41e23).

**Comment by Celtech** [comment]
> Thank you for your Feature Request, please update the latest version and try using `stylelint-config-tailwindcss/scss` instead of `stylelint-config-tailwindcss`，For details, see [commit](https://github.com/zhilidali/stylelint-config-tailwindcss/commit/62252359256671cca2179a2db12e28bbcab41e23).

Thanks for the quick work on this! Just tested it out and she's working perfectly!
